<MyLayout>
    do_default_tab:False
    size_hint: .8,.8
    pos_hint:{'center_x':.5,"center_y":.5}

    tab_pos:'left_top'


    TabbedPanelItem:
        text:"Tab 1"
        Label:
            text:'Hello World'

    TabbedPanelItem:
        text:"Tab 2"
        BoxLayout:
            Label:
                text:"Press the button =>"
            Button:
                text:'Click me '              

    TabbedPanelItem:
        text:"Tab 3`"     

        Image:
            source:""       